"""create eevent table

Revision ID: 2ba1c98cc199
Revises: 
Create Date: 2023-12-19 10:29:45.767639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba1c98cc199'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phonenumber', sa.String(length=15), nullable=True),
    sa.Column('selectedEvent', sa.String(length=100), nullable=True),
    sa.Column('numberoftickets', sa.Integer(), nullable=True),
    sa.Column('additionalInfo', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_email'), 'events', ['email'], unique=True)
    op.create_index(op.f('ix_events_firstname'), 'events', ['firstname'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_lastname'), 'events', ['lastname'], unique=False)
    op.create_index(op.f('ix_events_phonenumber'), 'events', ['phonenumber'], unique=False)
    op.create_index(op.f('ix_events_selectedEvent'), 'events', ['selectedEvent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_selectedEvent'), table_name='events')
    op.drop_index(op.f('ix_events_phonenumber'), table_name='events')
    op.drop_index(op.f('ix_events_lastname'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_firstname'), table_name='events')
    op.drop_index(op.f('ix_events_email'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
